import type { ResumeData } from "./types";

/**
 * Real data extracted from the uploaded CV of Abdul Qader Wadan,
 * restructured into a modern Senior Architectural Designer resume.
 */
export const sampleResume: ResumeData = {
  personal: {
    fullName: "Abdul Qader Wadan",
    jobTitle: "Senior Architectural Designer",
    email: "eng.qader@gmail.com",
    phone: "+93 787 308 321",
    location: "Kabul, Afghanistan",
    website: "",
    linkedin: "linkedin.com/in/abdulqaderwadan",
    portfolio: "",
    nationality: "Afghan",
    photo: "",
    summary:
      "Senior Architectural Designer and Engineering Coordinator with 17+ years of experience delivering public, commercial and humanitarian buildings across Afghanistan. Combines architectural design leadership with hands-on project management, quality control and cost estimation — from concept and IBC/Neufert-compliant documentation to site supervision and handover. Proven record coordinating multidisciplinary teams on schools, clinics, mosques, orphanages and WASH infrastructure for international donors including MBRCH, USACE and PRT-funded programmes.",
  },
  skills: [
    { id: "s1", name: "Architectural Design", level: 95 },
    { id: "s2", name: "Project Management", level: 92 },
    { id: "s3", name: "Concept Development", level: 88 },
    { id: "s4", name: "Construction Documentation", level: 94 },
    { id: "s5", name: "Interior Design", level: 82 },
    { id: "s6", name: "BIM Coordination", level: 80 },
    { id: "s7", name: "Quality Control & QA/QC", level: 93 },
    { id: "s8", name: "Cost Estimation & BOQ", level: 90 },
  ],
  software: [
    { id: "f1", name: "AutoCAD", level: 96 },
    { id: "f2", name: "Autodesk Revit", level: 82 },
    { id: "f3", name: "SketchUp", level: 90 },
    { id: "f4", name: "Lumion", level: 85 },
    { id: "f5", name: "3ds Max", level: 88 },
    { id: "f6", name: "V-Ray", level: 78 },
    { id: "f7", name: "Photoshop", level: 80 },
    { id: "f8", name: "Illustrator", level: 68 },
    { id: "f9", name: "InDesign", level: 65 },
    { id: "f10", name: "MS Project", level: 86 },
    { id: "f11", name: "Microsoft Office", level: 92 },
  ],
  languages: [
    { id: "l1", name: "Pashto", proficiency: "Native" },
    { id: "l2", name: "Dari", proficiency: "Native" },
    { id: "l3", name: "Urdu", proficiency: "Fluent" },
    { id: "l4", name: "English", proficiency: "Professional" },
  ],
  experience: [
    {
      id: "e1",
      company: "Zia Ayoubi Construction Company (ZACC)",
      position: "Architect & Engineering Coordinator",
      location: "Kabul, Afghanistan",
      startDate: "Jan 2025",
      endDate: "May 2026",
      current: false,
      responsibilities: [
        "Designed public buildings including commercial, residential, schools, clinics, orphanages, mosques and ablution facilities, with full shop drawing packages.",
        "Applied current engineering codes (IBC, Neufert) across all design and documentation stages.",
        "Produced 2D/3D drafting and detailing in AutoCAD and 3ds Max for tender and construction issue.",
        "Planned and organised project activities, implementation plans and master time schedules.",
        "Managed financial, material and staffing resources while coordinating all site works.",
        "Reviewed specifications, contract documents and as-built drawings as QC Engineer.",
        "Ran daily site inspections, weekly coordination meetings and prepared construction submittals.",
      ],
      achievements: [
        "Established a single coordinated drawing standard across architectural and MEP disciplines, reducing site RFIs and rework.",
        "Delivered concurrent public building packages on schedule while acting as designer, coordinator and QC lead.",
      ],
      projects:
        "Commercial and residential buildings, schools, clinics, orphanages, mosques and ablution buildings.",
    },
    {
      id: "e2",
      company: "Humanitarian Assistance Society (H.A.S)",
      position: "Architect & Engineering Coordinator",
      location: "Afghanistan (multi-province)",
      startDate: "Jul 2017",
      endDate: "Dec 2024",
      current: false,
      responsibilities: [
        "Led architectural design of schools, clinics, orphanages, mosques and community buildings nationwide.",
        "Designed and supervised WASH infrastructure: water wells, surface and elevated water tanks across multiple provinces.",
        "Designed and delivered hand-wash facilities at the IHH Orphanage in Jowzjan Province.",
        "Delivered ablution building design and construction across several provinces.",
        "Performed QC review of specifications, drawings and contract documents plus as-built verification.",
        "Handled project scheduling, estimating, site surveying, reporting and monitoring & evaluation.",
      ],
      achievements: [
        "Delivered seven years of continuous humanitarian construction programmes without a quality-driven project stoppage.",
        "Standardised WASH design details, enabling faster replication of water and sanitation facilities across provinces.",
      ],
      projects:
        "Nationwide WASH programme, IHH Orphanage Jowzjan, schools, clinics and mosques.",
    },
    {
      id: "e3",
      company:
        "Mohammad Bin Rashid Al Maktoum Humanitarian & Charity Establishment (MBRCH)",
      position: "Architect Designer / QC Manager / Operations Manager",
      location: "Kandahar, Afghanistan",
      startDate: "Oct 2013",
      endDate: "Jun 2017",
      current: false,
      responsibilities: [
        "Designed public buildings and produced IBC/Neufert-compliant shop drawings in AutoCAD and 3ds Max.",
        "Designed and constructed the water supply system for MBR Disabled People Town, Panjwaye District.",
        "Delivered the water supply system, hand-wash facilities and ablution building for Sheikh Sayed Orphanage, Kohkaran, Kandahar City.",
        "Managed QC: submittal review, as-built control, daily inspection and weekly coordination meetings.",
        "Directed general project operations — implementation plans, schedules and resource management.",
        "Prepared cost estimates and Bills of Quantity, including cost breakdown analysis for USACE and PRT projects.",
        "Carried out town planning: site survey and distribution of business, residential, public and road zones.",
      ],
      achievements: [
        "Delivered a complete potable-water network for a disabled persons' township, serving residents with year-round supply.",
        "Held six concurrent technical roles — design, WASH, QC, operations, estimation and town planning — on a single donor programme.",
      ],
      projects:
        "MBR Disabled People Town (Panjwaye), Sheikh Sayed Orphanage (Kohkaran).",
    },
    {
      id: "e4",
      company: "Sadiq Noor Construction Co. / Waheed Zia Construction Co. JV",
      position: "Architect Designer & Construction Manager",
      location: "Nangarhar, Afghanistan",
      startDate: "Jun 2012",
      endDate: "Sep 2013",
      current: false,
      responsibilities: [
        "Designed schools, clinics and mosques with full AutoCAD 2D/3D and 3ds Max documentation.",
        "Managed construction: daily, weekly and monthly reporting to head office.",
        "Ran site safety briefings with skilled and unskilled labour before each work phase.",
        "Controlled concrete quality — slump and air content checks, 7/14/21/28-day cylinder compression tests.",
        "Prepared BOQs and cost breakdown analysis for USACE, PRT and other donor projects.",
        "Delivered city planning services: site survey and urban zone distribution.",
      ],
      achievements: [
        "Implemented a structured concrete testing regime that maintained compliance across all pours.",
      ],
      projects: "Donor-funded schools, clinics and mosques in Nangarhar.",
    },
    {
      id: "e5",
      company: "Sadiq Noor Construction Co. / Urban Builders Group JV",
      position: "Architect Designer & QC / Submittals Manager",
      location: "Herat, Afghanistan",
      startDate: "Oct 2011",
      endDate: "May 2012",
      current: false,
      responsibilities: [
        "Created and maintained the project submittal log and all project-specific quality control reports.",
        "Reviewed shop drawings and submittals for conformance with project specifications.",
        "Conducted preparatory, initial and follow-up quality meetings for each definable feature of work.",
        "Verified materials against approved submittals and maintained daily as-built drawings.",
        "Exercised stop-work authority to resolve safety and quality matters.",
        "Controlled overall project delivery — labour, methods, code compliance and cost-effective procurement.",
      ],
      achievements: [
        "Built the JV's submittal control system from scratch, giving full traceability from approval to installation.",
      ],
      projects: "Public building programme, Herat.",
    },
    {
      id: "e6",
      company: "Sadiq Noor Construction Company (SNCC) — Head Office",
      position: "Architect Designer & Design Team Manager",
      location: "Kabul, Afghanistan",
      startDate: "May 2010",
      endDate: "Sep 2011",
      current: false,
      responsibilities: [
        "Led the in-house design team producing schools, clinics and mosque designs to IBC and Neufert standards.",
        "Delegated and reviewed team assignments and ran design quality reviews.",
        "Prepared and analysed budgets and financial reports for the design department.",
        "Trained the team on new business guidelines and design developments.",
        "Supervised projects: reporting standards, KPI dashboards, schedules and deliverables.",
        "Estimated USACE and PRT projects and scrutinised tender documents, drawings and schedules.",
      ],
      achievements: [
        "Set the company's design quality directives and reporting standards still used across projects.",
      ],
      projects: "Head-office design portfolio for national public building tenders.",
    },
    {
      id: "e7",
      company: "Mohammad Bin Rashid Al Maktoum Charitable Foundation (MBR)",
      position: "Architect Designer, Surveyor & Interior Designer",
      location: "Afghanistan",
      startDate: "Jan 2009",
      endDate: "Apr 2010",
      current: false,
      responsibilities: [
        "Assembled site data and produced rough and detailed scale plans for foundations, buildings and structures.",
        "Analysed technical implications of design concepts — weights, volumes and stress factors.",
        "Designed interior spaces, floor/wall textures, colour schemes and material selections.",
        "Laid out interior room arrangements for commercial buildings using CAD.",
        "Operated survey instruments including EDM to collect site data and set out stakes and marks.",
        "Built landscape, architectural and display models.",
      ],
      achievements: [
        "Delivered combined architecture, interior and survey services as a single point of technical responsibility.",
      ],
      projects: "Charitable foundation building programme.",
    },
    {
      id: "e8",
      company: "Atal Yadgar Construction & Engineering Company",
      position: "Architect Surveyor & Draftsman",
      location: "Afghanistan",
      startDate: "Jun 2007",
      endDate: "Dec 2008",
      current: false,
      responsibilities: [
        "Surveyed ancient houses and heritage buildings and produced measured drawings.",
        "Mapped projects and prepared complete drawing sets.",
        "Drew, modified and plotted technical drawings for construction issue.",
      ],
      achievements: [
        "Documented heritage structures through accurate measured survey drawings.",
      ],
      projects: "Heritage survey and documentation projects.",
    },
  ],
  education: [
    {
      id: "ed1",
      degree: "Bachelor of Architecture — Engineering Faculty",
      institution: "Kabul University",
      location: "Kabul, Afghanistan",
      year: "2009",
      details:
        "Architecture Department. Studies covering architectural design, building technology, structures and urban planning.",
    },
    {
      id: "ed2",
      degree: "High School Diploma (12th Grade)",
      institution: "Yusuf Abad High School, Bajaur",
      location: "Pakistan",
      year: "1996",
      details: "",
    },
  ],
  projects: [
    {
      id: "p1",
      name: "MBR Disabled People Town — Water Supply System",
      category: "Infrastructure / WASH",
      location: "Panjwaye District, Kandahar",
      year: "2014",
      area: "Township scale",
      client: "MBRCH",
      role: "Design & WASH Engineer",
      responsibilities:
        "Full water supply system design and construction supervision for a residential township for people with disabilities, including source, storage and distribution network.",
      software: ["AutoCAD", "MS Project", "Excel"],
      image: "",
    },
    {
      id: "p2",
      name: "Sheikh Sayed Orphanage — Facilities Package",
      category: "Institutional",
      location: "Kohkaran, Kandahar City",
      year: "2015",
      area: "Campus facilities",
      client: "MBRCH",
      role: "Architect Designer & QC Manager",
      responsibilities:
        "Water supply system, student hand-wash facilities and ablution building — design, documentation and site supervision through to handover.",
      software: ["AutoCAD", "3ds Max", "SketchUp"],
      image: "",
    },
    {
      id: "p3",
      name: "IHH Orphanage — Hand Wash Facilities",
      category: "Humanitarian / WASH",
      location: "Jowzjan Province",
      year: "2019",
      area: "Facility block",
      client: "Humanitarian Assistance Society",
      role: "Architect & WASH Engineer",
      responsibilities:
        "Designed and delivered sanitation and hand-wash facilities for orphanage students, including layout, detailing and construction supervision.",
      software: ["AutoCAD", "Lumion"],
      image: "",
    },
    {
      id: "p4",
      name: "National WASH Programme — Wells & Water Tanks",
      category: "Infrastructure",
      location: "Multi-province, Afghanistan",
      year: "2017–2024",
      area: "Multi-site",
      client: "Humanitarian Assistance Society",
      role: "Engineering Coordinator",
      responsibilities:
        "Survey, design and construction of water wells, surface water tanks and elevated water tanks across multiple provinces, with standardised repeatable detailing.",
      software: ["AutoCAD", "MS Project"],
      image: "",
    },
    {
      id: "p5",
      name: "Public Schools & Clinics Programme",
      category: "Education / Healthcare",
      location: "Nangarhar & Herat",
      year: "2011–2013",
      area: "Multiple buildings",
      client: "USACE / PRT funded",
      role: "Architect Designer & QC Manager",
      responsibilities:
        "Architectural design, shop drawings, submittal control and construction quality management for donor-funded schools and clinics.",
      software: ["AutoCAD", "3ds Max"],
      image: "",
    },
    {
      id: "p6",
      name: "Community Mosques & Ablution Buildings",
      category: "Religious / Community",
      location: "Multi-province, Afghanistan",
      year: "2013–2026",
      area: "Various",
      client: "Multiple donors",
      role: "Lead Architect",
      responsibilities:
        "Concept through construction documentation for mosques and ablution buildings, balancing traditional form with efficient modern construction.",
      software: ["AutoCAD", "SketchUp", "Lumion", "3ds Max"],
      image: "",
    },
  ],
  awards: [],
  certifications: [
    {
      id: "c1",
      title: "IBC & Neufert Applied Design Standards",
      subtitle: "Applied in professional practice",
      year: "",
    },
    {
      id: "c2",
      title: "Microsoft Project — Planning & Scheduling",
      subtitle: "Project planning and scheduling software",
      year: "",
    },
  ],
  memberships: [],
  publications: [],
  workshops: [
    {
      id: "w1",
      title: "Excel BOQ Automation Formats",
      subtitle: "Self-developed estimating templates adopted across projects",
      year: "",
    },
    {
      id: "w2",
      title: "Proposal Writing & Management Tools",
      subtitle: "Developed internal management and reporting tools",
      year: "",
    },
  ],
  references: [
    {
      id: "r1",
      name: "Eng. Najeebullah Hussain Kheil",
      title: "Mechanical Design Team Manager",
      phone: "+93 700 001 298",
      email: "nh8239@gmail.com",
    },
    {
      id: "r2",
      name: "Hashmatullah Majede",
      title: "Project Manager",
      phone: "+93 700 474 441",
      email: "eng.hashmat@yahoo.com",
    },
  ],
  sectionOrder: [
    "experience",
    "projects",
    "education",
    "certifications",
    "workshops",
    "awards",
    "memberships",
    "publications",
    "references",
  ],
  hiddenSections: [],
  theme: {
    navy: "#152238",
    accent: "#B99770",
    charcoal: "#2F3640",
    fontFamily: "Inter",
    density: "normal",
    layout: "sidebar-left",
    showBlueprint: true,
  },
};

export const emptyResume: ResumeData = {
  ...sampleResume,
  personal: {
    fullName: "",
    jobTitle: "Senior Architectural Designer",
    email: "",
    phone: "",
    location: "",
    website: "",
    linkedin: "",
    portfolio: "",
    nationality: "",
    photo: "",
    summary: "",
  },
  experience: [],
  education: [],
  projects: [],
  certifications: [],
  workshops: [],
  references: [],
};
