/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerateRouteImport } from './routes/generate'

const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/generate': typeof GenerateRoute
}
export interface FileRoutesByTo {
  '/generate': typeof GenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/generate': typeof GenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/generate'
  fileRoutesByTo: FileRoutesByTo
  to: '/generate'
  id: '__root__' | '/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GenerateRoute: typeof GenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  GenerateRoute: GenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
